# Vue Automations

theme: MonTableau
title: Automations
path: vue-page-automations
icon: ios:robot#fullcolor
type: panel
badges: []
cards:
  - type: custom:dwains-flexbox-card
    items_classes: "col-xs-12"
    cards:
    
      - type: custom:swiss-army-knife-card
        disable_card: true
        layout:
          template:
            name: sak_layout_mjt_barre_pieces
            variables:
              - sak_layout_mjt_barre_pieces_titre: 'Automations'
              - sak_layout_mjt_barre_pieces_image: '/local/mes_images/robot.svg'
              
      - type: custom:dwains-flexbox-card
        items_classes: "col-xs-12"
        cards:
          - type: custom:scheduler-card
            include:
              - vacuum
              - group
              - switch
              - light
              - alarm_control_panel
              - scene
              - climate
