# Vue Automations

theme: MonTableau
title: Automations
path: vue-page-automations
icon: ios:robot#fullcolor
type: panel
badges: []
cards:
  - type: custom:dwains-flexbox-card
    items_classes: "col-xs-12"
    cards:
      - type: custom:dwains-flexbox-card
        items_classes: "col-xs-12 col-sm-4"
        cards:
          - type: custom:button-card
            icon: ios:robot#fullcolor
            tap_action: none
            size: 100%
            styles:
              card:
                - height: 60px
              icon:
                - color: "#0099cc"
            card_mod:
              style: |
                ha-card {
                margin-left: auto;
                margin-right: auto;
                }

          - type: custom:button-card
            name: Automations
            tap_action: none
            styles:
              card:
                - height: 60px
                - font-size: 10px
                - color: "#0099cc"
              name:
                - text-transform: uppercase
                - letter-spacing: 0.3em
                - font-familly: AppleGothic
                - justify-self: center
                - padding: 0px 5px
                - font-size: 25px
            card_mod:
              style: |
                ha-card {
                margin-left: auto;
                margin-right: auto;
                }

          - type: custom:button-card
            icon: ios:retour-maison#fullcolor
            size: 100%
            styles:
              card:
                - height: 60px
            tap_action:
              action: navigate
              navigation_path: vue-page-Information
            card_mod:
              style: |
                ha-card {
                margin-left: auto;
                margin-right: auto;
                }

      - type: custom:dwains-flexbox-card
        items_classes: "col-xs-12"
        cards:
          - type: custom:scheduler-card
            include:
              - vacuum
              - group
              - switch
              - light
              - alarm_control_panel
              - scene
              - climate
