sensor:

  - platform: rest
    resource: "https://www.hydroquebec.com/data/documents-donnees/donnees-ouvertes/json/demande.json"
    name: Demande de puissance réseau Hydro-Québec
    unique_id: edbb1dd6-6160-4279-a64d-3acc146121e5
    json_attributes:
    unit_of_measurement: MW
    device_class: power
    state_class: measurement
    value_template: >
     {% set index =  value_json.indexDonneePlusRecent %}
     {{ value_json.details[index]["valeurs"]["demandeTotal"] }}

rest:
  - resource: https://www.hydroquebec.com/data/documents-donnees/donnees-ouvertes/json/production.json
    scan_interval: 3600 
    sensor:
      - name: "Hydro-Québec production total 2"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.total }}'
        device_class: power
        unit_of_measurement: "MW"
      - name: "Hydro-Québec production hydraulique 2"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.hydraulique }}'
        device_class: power
        unit_of_measurement: "MW"
      - name: "Hydro-Québec production éolien 2"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.eolien }}'
        device_class: power
        unit_of_measurement: "MW"
      - name: "Hydro-Québec production autres 2"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.autres }}'
        device_class: power
        unit_of_measurement: "MW"
      - name: "Hydro-Québec production solaire 2"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.solaire }}'
        device_class: power
        unit_of_measurement: "MW"
      - name: "Hydro-Québec production thermique 2"
        value_template: '{{ value_json.details[value_json.indexDonneePlusRecent].valeurs.thermique }}'
        device_class: power
        unit_of_measurement: "MW"