sensor:

# Pamètres non disponible indirectement

  - platform: template
    sensors:
      meteo_def_detecteurs_conditions_actuelles:
        friendly_name: "Conditions Actuelles"
        value_template: "{{ states('weather.tempest_st_00032986_shawinigan_sud_hourly') }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_prevision_precipitation:
        friendly_name: "Prévisions Précipitation"
        icon_template: mdi:weather-rainy
        unit_of_measurement: "%"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[0]['precipitation_probability'] }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_conditions_actuelles_j0:
        friendly_name: "Conditions Actuelles jour 00"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[0]['condition'] }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_conditions_actuelles_j1:
        friendly_name: "Conditions Actuelles jour 01"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[1]['condition'] }}"       
        
  - platform: template
    sensors:
      meteo_def_detecteurs_conditions_actuelles_j2:
        friendly_name: "Conditions Actuelles jour 02"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[2]['condition'] }}"        
        
  - platform: template
    sensors:
      meteo_def_detecteurs_conditions_actuelles_j3:
        friendly_name: "Conditions Actuelles jour 03"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[3]['condition'] }}"           
        
  - platform: template
    sensors:
      meteo_def_detecteurs_conditions_actuelles_j4:
        friendly_name: "Conditions Actuelles jour 04"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[4]['condition'] }}"    
        
  - platform: template
    sensors:
      meteo_def_detecteurs_conditions_actuelles_j5:
        friendly_name: "Conditions Actuelles jour 05"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[5]['condition'] }}"    

  - platform: template
    sensors:
      meteo_def_detecteurs_temperature_j0:
        friendly_name: "Conditions Actuelles temperature jour 0"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[0]['temperature'] }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_temperature_j1:
        friendly_name: "Conditions Actuelles temperature jour 01"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[1]['temperature'] }}"       
        
  - platform: template
    sensors:
      meteo_def_detecteurs_temperature_j2:
        friendly_name: "Conditions Actuelles temperature jour 02"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[2]['temperature'] }}"        
        
  - platform: template
    sensors:
      meteo_def_detecteurs_temperature_j3:
        friendly_name: "Conditions Actuelles temperature jour 03"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[3]['temperature'] }}"           
        
  - platform: template
    sensors:
      meteo_def_detecteurs_temperature_j4:
        friendly_name: "Conditions Actuelles temperature jour 04"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[4]['temperature'] }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_temperature_j5:
        friendly_name: "Conditions Actuelles temperature jour 05"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[5]['temperature'] }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_templow_j0:
        friendly_name: "Conditions Actuelles templow jour 00"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[0]['templow'] }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_templow_j1:
        friendly_name: "Conditions Actuelles templow jour 01"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[1]['templow'] }}"       
        
  - platform: template
    sensors:
      meteo_def_detecteurs_templow_j2:
        friendly_name: "Conditions Actuelles templow jour 02"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[2]['templow'] }}"        
        
  - platform: template
    sensors:
      meteo_def_detecteurs_templow_j3:
        friendly_name: "Conditions Actuelles templow jour 03"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[3]['templow'] }}"           
        
  - platform: template
    sensors:
      meteo_def_detecteurs_templow_j4:
        friendly_name: "Conditions Actuelles templow jour 04"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[4]['templow'] }}"     
        
  - platform: template
    sensors:
      meteo_def_detecteurs_templow_j5:
        friendly_name: "Conditions Actuelles templow jour 05"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[5]['templow'] }}"           
        
  - platform: template
    sensors:
      meteo_def_detecteurs_precipitation_probability_j0:
        friendly_name: "Conditions Actuelles precipitation_probability jour 0"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[0]['precipitation_probability'] }}"
        
  - platform: template
    sensors:
      meteo_def_detecteurs_precipitation_probability_j1:
        friendly_name: "Conditions Actuelles precipitation_probability jour 1"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[1]['precipitation_probability'] }}"       
        
  - platform: template
    sensors:
      meteo_def_detecteurs_precipitation_probability_j2:
        friendly_name: "Conditions Actuelles precipitation_probability jour 2"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[2]['precipitation_probability'] }}"        
        
  - platform: template
    sensors:
      meteo_def_detecteurs_precipitation_probability_j3:
        friendly_name: "Conditions Actuelles precipitation_probability jour 3"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[3]['precipitation_probability'] }}"           
        
  - platform: template
    sensors:
      meteo_def_detecteurs_precipitation_probability_j4:
        friendly_name: "Conditions Actuelles precipitation_probability jour 4"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[4]['precipitation_probability'] }}"  

  - platform: template
    sensors:
      meteo_def_detecteurs_precipitation_probability_j5:
        friendly_name: "Conditions Actuelles precipitation_probability jour 5"
        value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[5]['precipitation_probability'] }}"       
        
  - platform: template
    sensors:
       meteo_def_detecteurs_precipitation_j0:
         friendly_name: "Conditions Actuelles precipitation jour 0"
         value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[0]['precipitation'] }}"
         
  - platform: template
    sensors:
       meteo_def_detecteurs_precipitation_j1:
         friendly_name: "Conditions Actuelles precipitation jour 1"
         value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[1]['precipitation'] }}"       
        
  - platform: template
    sensors:
       meteo_def_detecteurs_precipitation_j2:
         friendly_name: "Conditions Actuelles precipitation jour 2"
         value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[2]['precipitation'] }}"        
        
  - platform: template
    sensors:
       meteo_def_detecteurs_precipitation_j3:
         friendly_name: "Conditions Actuelles precipitation jour 3"
         value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[3]['precipitation'] }}"           
        
  - platform: template
    sensors:
       meteo_def_detecteurs_precipitation_j4:
         friendly_name: "Conditions Actuelles precipitation jour 4"
         value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[4]['precipitation'] }}"   
         
  - platform: template
    sensors:
       meteo_def_detecteurs_precipitation_j5:
         friendly_name: "Conditions Actuelles precipitation jour 5"
         value_template: "{{ state_attr('weather.tempest_st_00032986_shawinigan_sud_daily', 'forecast')[5]['precipitation'] }}"       
        
        
    
        
        
        